sudo: required
services:
  - docker

before_install:
  - docker build -t jeremybamaddox/frontend-study-cards -f ./frontend-study-cards/Dockerfile.dev ./frontend-study-cards

script:
  - docker run -e CI=true jeremybamaddox/frontend-study-cards npm test 

after_success:
  - docker build -t jeremybamaddox/frontend-study-cards ./frontend-study-cards
  - docker build -t jeremybamaddox/api-study-cards ./api-study-cards
  - docker build -t jeremybamaddox/router-study-cards ./router-study-cards
  # Log into docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push built images to docker hub
  - docker push jeremybamaddox/frontend-study-cards
  - docker push jeremybamaddox/api-study-cards
  - docker push jeremybamaddox/router-study-cards

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: study-cards
  env: Studycards-env
  bucketname: elasticbeanstalk-us-east-2-162194444266
  bucket-path: docker-study-cards
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
