version: '3'
services:
  api:
    build:
      context: ./api-study-cards
      dockerfile: Dockerfile.dev
    volumes:
      - /home/node/app/node_modules
      - ./api-study-cards:/home/node/app
    env_file:
      - ./.env.development.local
  client:
    build:
      context: ./frontend-study-cards
      dockerfile: Dockerfile.dev
    volumes:
      - /home/node/app/node_modules
      - ./frontend-study-cards:/home/node/app
  router:
    depends_on:
      - api
      - client
    build:
      context: ./router-study-cards
      dockerfile: Dockerfile.dev
    ports:
      - '9090:5000'
