version: '3'
services:
  api-tests:
    build:
      context: ./api-study-cards
      dockerfile: Dockerfile.dev
    volumes:
      - /home/node/app/node_modules
      - ./api-study-cards:/home/node/app
    command: [ "npm", "run", "test" ]
  client-tests:
    build:
      context: ./frontend-study-cards
      dockerfile: Dockerfile.dev
    volumes:
      - /home/node/app/node_modules
      - ./frontend-study-cards:/home/node/app
    command: [ "npm", "run", "test" ]
